- cdn_definitions/schema.json
- cdn_definitions/schema.yaml
- docs/data.rst
- docs/userguide.rst
This is ultimately expected to be hosted under release-engineering,
but let's not use those URLs until that happens, since links are
all broken otherwise.
> docs: use user namespace for links while experimental

- CHANGELOG.md
- docs/userguide.rst
- src/cdn_definitions/_impl/__init__.py
- tests/test_load.py
This will be used by the cdn-definitions RPM package.
Load path can also be customized via CDN_DEFINITIONS_PATH env var.
> Support loading data from /usr/share/cdn-definitions

- CHANGELOG.md
- src/cdn_definitions/data.json
- src/cdn_definitions/data.yaml
I've gone through and checked all RHUI aliases against actual
data on CDN. This one seems to be incorrect:
1. on current CDN filesystem, the rhui path doesn't exist at all
2. on older filesystem, it exists, but is not symlinked to non-rhui
3. on older filesystem, content between rhui and non-rhui paths
doesn't appear to be identical
4. the relevant content sets were disabled in 2014 (rcm-metadata
ec3025f411e46c)
Hence this is not actually a valid RHUI alias.  It was probably
intended to be, so an argument could be made for keeping it, but
it would force us to change point (3) above and start serving
identical content for the two paths, and there's not really any
benefit to making such a change now, only risk.
> RHUI: drop /content/fastrack/rhel/rhui alias

- setup.py
Enables links to docs and changelog to appear on the PyPI entry.
> Add project URLs for PyPI

- docs/maint.rst
That project was renamed to exodus-lambda.
> docs: fix outdated reference to cdn-lambda

- scripts/make-json
- src/cdn_definitions/data.json
- src/cdn_definitions/data.yaml
Currently, no RHEL 8 E4S content is available on RHUI, but it is needed for the same reasons that RHEL 7 E4S content is available.
Also included in this PR is a patch that I needed in order to follow the (excellent and thorough) contribution guide.
> Add RHEL 8 E4S link for RHUI

- src/cdn_definitions/data.json
- src/cdn_definitions/data.yaml
Currently, no RHEL 8 EUS content is available on RHUI, but it is needed
for the same reasons that RHEL 7 EUS content is available.
> Add RHEL 8 EUS link for RHUI

- src/cdn_definitions/data.json
- src/cdn_definitions/data.yaml
Currently, no RHEL 8 AUS content is available on RHUI, but it is needed
for the same reasons that RHEL 7 AUS content is available.
> Add RHEL 8 AUS link for RHUI

- constraints-legacy.txt
- tox.ini
The python2.7 installation of pyresistent (a jsonschema dependency)
fails with the following error message:
"pyrsistent requires Python '>=3.5' but the running Python is 2.7.15"
Pyrsistent reportedly dropped python2.7 support [1]. Py2.7 installs
of jsonschema must pin the latest pyresistent version with python2.7
support (pyrsistent-0.16.1) to avoid an installation error.
[1] https://github.com/tobgu/pyrsistent/issues/208
> pyrsistent install fails on py2.7

- tox.ini
The commit which moved PyYAML from test-requirements.txt into a
newly created requirements.txt file (44045c5), was developed in
parallel with the commit which specified the py27 tox environment's
dependencies (a2aba3c). As such, the py27 tox environment's
dependencies did not include requirements.txt. This resulted in the
exclusion of PyYAML from the py27 tox environment.
> Add requirements.txt as a dependency of py27 tox env

- docs/userguide.rst
- requirements.txt
- src/cdn_definitions/__init__.py
- src/cdn_definitions/_impl/__init__.py
- test-requirements.txt
- tests/test_load.py
The load_schema API allows clients to more easily consume the
schema.json file that is included in the cdn-definitions package.
The load_data API will return a raw dictionary of the chosen data
file. This will allow users to access various types of data in a
uniform way.
In order to encourage a single, consistent method of access to
the cdn-definitions data, the legacy access methods and related
classes (i.e., PathAlias, rhui_alias, and origin_alias) will be
deprecated. A dedicated Python object will no longer need to be
created for each new addition to the schema.
The load_data API also includes an optional "source" argument to
the load_data method. The source parameter allows the user to
specify the source of the cdn_definitions JSON or YAML data file.
The source could be a URL or a …
> Create load_data and load_schema APIs [RHELDST-4862]

- MANIFEST.in
- setup.py
requirements.txt was introduced recently in 44045c557ea0b1c237.
However, this does not actually do anything during "pip install",
which only looks at install_requires metadata.
Here we copy the convention used from most of our other projects:
just reuse requirements.txt for install_requires. This ensures
"pip install cdn-definitions" will install dependencies.
> Fix requirements.txt not used

- src/cdn_definitions/data.json
- src/cdn_definitions/data.yaml
- src/cdn_definitions/schema.json
- src/cdn_definitions/schema.yaml
Adding rhel_open_dist that will return list of  RHEL major versions which are still expecting new minor releases
Refers to [RHELDST-2517]
> Adding rhel_open_dist listing active RHEL versions 

- src/cdn_definitions/_impl/__init__.py
Fixes
TypeError: unsupported operand type(s) for -=: 'Retry' and 'int'
Sufficiently new versions of requests module bundle its own urllib3,
which makes the whole Session-HTTPAdapter-Retry chain behave
unexpectedly. HTTPAdapter always calls Retry.from_int() regardless
of the max_retries parameter type. Retry.from_int() method either
creates a new instance of Retry or compares if the parameter already
is a Retry instance and returns it unchanged. The problem here is
that urllib3.util.retry.Retry is not the same as
requests.packages.urllib3.util.retry.Retry, so the non-bundled retry
object is wrapped into the bundled Retry object and is treated
as integer from then on, leading to the TypeError above.
RHEL-6 and RHEL-7 python-requests packages ship their own version of …
> Use urllib3.util.retry from requests.packages [RHELDST-5671]

- requirements.txt
- src/cdn_definitions/_impl/__init__.py
- tests/test_load.py
CDN Definitions should be immutable for anyone consuming them, to prevent unintentional
(or even intentional, but wildly incorrect) modification on-the-fly while consuming the
definitions. This commit tries to ensure the immutability by returning all dictionaries
as frozendicts and all lists an frozenlists (using frozenlist2 module)
This change is compatible even with python 2.6, however el6eng and el7eng packages
of frozendict and frozenlist2 don't exist and there is no intent to create them, so
even though the requirements for these are are listed in requirements.txt without
restrictions, there is a fallback to builtin dict and/or list if they are not installed.
> Return definitions data as frozendict/frozenlist where possible [RHELDST-5671]

- src/cdn_definitions/data.json
- src/cdn_definitions/data.yaml
- src/cdn_definitions/schema.json
- src/cdn_definitions/schema.yaml
This variable drives the population of all ubi DOT repos to pulp. If set
to False, none ubi DOT repo will be populated.
> Add populate_ubi_dot_repos variable [RHELDST-6389]

- .github/CODEOWNERS
Three is the ideal number of owners while this project only had two.
I think it makes sense to add Caleigh here since she did various work
in this area, and due to the connection with exodus projects.
> Nominate additional CODEOWNER

- src/cdn_definitions/schema.json
- src/cdn_definitions/schema.yaml
The schema here attempted to require certain properties, but this had no
effect because the correct keyword is "required", not
"requiredProperties". This can be confirmed at
http://json-schema.org/draft-07/schema.
So, in reality we have never required any properties here.
We could now change this to "required" to match the original intent,
but I think it's reasonable to just drop them instead since:
- adding new required properties is backwards-incompatible. In the
worst-case scenario it breaks some services; in the best case it
probably breaks at least some tests.
- it anyway seems more user-friendly to allow these fields to be
omitted, since they always have some obvious default value
which could be provided (such as an empty list or dict). These could
even be filled in by the library …
> Drop ineffective requiredProperties

- constraints-legacy.txt
jsonschema dropped support for python2 in v4.0.1 [1], and v4.0.0
was yanked [2]. jsonschema-3.2.0 is the latest release that contains
py27 support.
[1] https://github.com/Julian/jsonschema/releases/tag/v4.0.1
[2] https://pypi.org/project/jsonschema/4.0.0/
> Constrain py27 install of jsonschema to v3.2.0

- src/cdn_definitions/data.json
- src/cdn_definitions/data.yaml
- src/cdn_definitions/schema.json
- src/cdn_definitions/schema.yaml
Added support for definition of override for final releasever
by content set label.
Additionally the pre-commit re-organized json files a bit.
> Added mapping for final releasever override [RHELDST-19153]

- .github/workflows/tests.yml
- tox.ini
Upload to Codecov fails without a token from
the forks and also enforced rate limiting.
Hence, remove the upload to Codecov. Instead,
configure the pytest failure on coverage below
100% for the tox cov jobs.
> Remove coverage upload to Codecov

- src/cdn_definitions/data.json
- src/cdn_definitions/data.yaml
- src/cdn_definitions/schema.json
- src/cdn_definitions/schema.yaml
Recently created rhui tooling products and content sets caused issues for downstream tools, such as Manifest-API.  This is because their download_urls contained "/rhui", which erroneously set the for_rhui property to true.
This issue has been fixed, but we would like to extend the solution to make it more robust. This change adds a new rhui_product_ids entry to the schema, so we can compare against a list of IDs rather than a single one. This was done to avoid breaking changes.
> Convert RHUI product ID to list of IDs [RHELDST-28614]
